### PR TITLE
add to_array_of

### PR DESCRIPTION
**Pull request by yaito3014**

### CODE REVIEW

**Comment by yaito3014** [comment]
[original `make_array` or `array_of` paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4065.html) banned narrowing conversion, but should it be permitted?

**Comment by saki7** [comment]
Yes this `yk::to_array_of` should explicitly call `static_cast`. Without the cast it will essentially be the same as calling `std::array`'s constructors or `std::to_array`, which are already defined in the standard.

The most realistic use-case of `yk::to_array_of` is when you're creating an array of `enum class` from an initializer list of integers, which AFAIK is currently introducing a QOL issue since it can not be easily done by standard interfaces.

**Comment by saki7** [comment]
Can you add a test case for

```cpp
enum class StrongID : int {};
constexpr auto predefined_ids = yk::to_array_of<StrongID>(1, 2, 3);
```

**Review by saki7 — COMMENTED** [review]
Can you add a test case for

```cpp
enum class StrongID : int {};
constexpr auto predefined_ids = yk::to_array_of<StrongID>(1, 2, 3);
```

**Comment by saki7** [comment]
LGTM

**Pull request merged**
